# Generated by Django 6.0.4 on 2026-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alumni_blog_committeemember_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alumni/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='committee/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
