# Generated by Django 6.0.4 on 2026-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notice_image_alter_alumni_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
