# Generated by Django 6.0.4 on 2026-04-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alumni_details_committeemember_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sort_order', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='committeemember',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.committeeacademicyear'),
        ),
    ]
