# Generated by Django 6.0.4 on 2026-04-15 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_committeeacademicyear_alter_committeemember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('batch', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_profiles/')),
                ('designation', models.CharField(max_length=120)),
                ('year_label', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
