# Generated by Django 6.0.4 on 2026-04-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pendingalumnisubmission_pendingblogsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
