# Generated by Django 6.0.4 on 2026-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alumni_facebook_url_alumni_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingalumnisubmission',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingalumnisubmission',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
